### ISSUE TITLE
not showing up

### ISSUE THREAD

**Issue by Dani-Briggs** [Montana-Media-Arts/120_CreativeCoding#177] opened 2018-11-08 00:02 UTC
Hi I'm trying to do a combination of the two example from the website, to create some buzzing bees. My problem is that nothing is showing up. Here's my code. `// setting varables
let bee = [];
let num_of_bees = 35;
let bg_color;

//setup
function setup(){
  createCanvas(windowWidth, 300);
  bg_color = color(45, 255, 163);

  for (let i = 0; i < num_of_bees; i++) {
        bee.push( new BuzzBee() );
    }

}

function draw(){
  background(bg_color);

  for (var i = 0; i < bee.length; i++) {
        bee[i].frame();

  }
}

//creating the class
class BuzzBee {
  constructor() {
    this.x = x;
    this.y = y;
    this.size_h(20, 50);
    this.size_w(20, 50);
    this.loc_x = random(width);
    this.loc_y = random(height);
    this.body_color = color(235, 180, 5);
    this.eye_x = this.size_h * 0.23 * -1;
    this.eye_y = this.size_w * 0.15;
    this.eye_size = this.size_w * 0.25;
    this.ant_x = this.eye_x * 1.5;
    this.ant_y = this.eye_y * 2.5;
    this.ant_size this.eye_size * 0.5;
    this.feet_x = this.size_w * 0.25;
    this.feet_y = this.size_h * 0.5;
    this.feet_w = this.size_w * 0.5;
    this.feet_h = this.size_h * 0.4;
    this.left_foot_angle = 0;
    this.right_foot_angle = 0;
  }

display(){

  push();

//body
  translate(this.loc_x, this.loc_y);
  fill(this.body_color);

  ellipse(0, 0, this.size_w, this.size_h);

//eye
  fill(255);
  ellipse(-this.eye_x, this.eye_y, this.eye_size, this.eye_size);
  ellipse(this.eye_x, this.eye_y, this.eye_size, this.eye_size);

//anntena
fill(5);
ellipse(-this.ant_x, this.ant_y, this.ant_size, this.ant_size);
ellipse(this.ant_x, this.ant_y, this.ant_size, this.ant_size);

//feet
  push();
  rotate(PI * (this.right_foot_angle * 0.01));
  translate(this.feet_x, this.feet_y);
  scale(1,-1);
  arc(0, 0, this.feet_w, this.feet_h, 0, PI, CHORD);
  pop();

  push();
  rotate(PI * -(this.left_foot_angle * 0.01));
  translate(-this.feet_x, this.feet_y);
  scale(1,-1);
  arc(0, 0, this.feet_w, this.feet_h, 0, -PI, CHORD);
  pop();

  pop();

move(){
  this.x = this.x + random(-5,5);
  this.y = this.y + random(-5,5);

}

}

}`

**Comment by DVSnell** [comment] 2018-11-08 00:42
I actually really like debugging...

Line 23:  You're calling for the `frame` function, but such a function doesn't exist. Adding `frame(){this.display();this.move();}`
between your constructor and your display function in your object should work.

Line 29: `x` doesn't exist yet.  You can make a global variable that is just `let x;` into your upper variables area. This will also be a problem with `y` on Line 30.

Lines 33: and 34 are both being treated as functions instead of variables.  And since they don't exist...  I think you want to put `this.size_h = random (20, 50);` on those lines (changing for size_w and your specific options,of course) to actually get some values.

Line 41: `this.ant_size this.eye_size * 0.5` Do what to what with what?  Probably just missing `=`

Line 85 Doesn't close off the `display` part of our object.  Throw a `}` on Line 86 and delete the one on Line 93.

**Comment by hayliesunshine** [comment] 2018-11-08 03:49
I am having the same problem. Here is my code. @DVSnell , the best that I could I applied your suggestions for Dani to what I have going on in my code. What I'm trying to make happen is a grid of stop lights, all the same size, that will move across the screen. Does anyone know why my code isn't showing up?

![capture](https://user-images.githubusercontent.com/42792278/48176705-92de9080-e2ce-11e8-8ed7-3f43f4559f20.JPG)
![capture2](https://user-images.githubusercontent.com/42792278/48176708-970aae00-e2ce-11e8-95e8-fdb52bc9447a.JPG)

**Comment by DVSnell** [comment] 2018-11-08 04:51
Here we go!

You're declaring your object inside the `draw` function so it's looking for `changingLight` outside and can't find it.  That makes it throw an error.  Add a `{` at Line 20 and delete the `}` on Line 68 to rectify that.  

Next up, we get to a whole cluster of undefined variables.  Basically, line 25 is the first time the script sees `x`, `y`, `w`, and `h` so if you declare them earlier it should fix things up a bit.  For my test, I just declared them globally below the array declarations using `let x;` and the like.

Now we have a pretty simple type error on Line 28 (Line 32, if you added the `lets` from the previous step) that is making it so the script is trying to use a function called `h`.  This is easy to fix by changing `h(3/4)` to `h * (3/4)` to work within the mathematical rules of p5 and javascript.

We have a similar problem in the `display` function.  `this.base_rect();`, `this.green_light();`, and the rest of them are all trying to be used as functions.  I think to alleviate this you need to declare each possible variable in your object property declarations like `this.base_rectX = x`, `this.base_rect_Y = y`, and so on.  Or you can use fixed values in the actual `display` function using `rect( chosen variables go here )` and the like.  It's a lot more initial work, but it will solve the problem and make it so you only need to change one line of code in order to create a global change to all objects.

Another thing is you will need to make sure you put `this.` in front of the color fills.  Otherwise it will look for a variable that hasn't been declared/doesn't exist.

Lastly, make sure you put stuff inside the `light` function, or comment it and it's reference in the `frame` function out or you might get "general weirdness" trying to preview your work.

**Comment by JoleneTiffanyG** [comment] 2018-11-08 05:32
Don (or whoever, but probably Don) I know this is probably a huge mess to try and troubleshoot but I can't get ANYTHING to show up and it's so frustrating..  My end goal was to try and get the orbs to all start at different points and then disappear when they hit the center of the canvas (I haven't written the start point yet) but all of this just seems completely wrong so far, I can't even get the canvas to show up
![screenshot 27](https://user-images.githubusercontent.com/42923897/48179537-f1127000-e2dc-11e8-8c98-f572a1f825b4.png)
![screenshot 28](https://user-images.githubusercontent.com/42923897/48179538-f1127000-e2dc-11e8-9ad5-8c6de5ab926f.png)

**Comment by DVSnell** [comment] 2018-11-08 06:15
Wheeeee!

So you're calling the function `orb.display`, but that doesn't exist.  Try using `orb.show();` on Line 26 instead.  Now we can see... well, something.  But it still doesn't work properly.

I'm not sure what you were going for using `+-` on lines 55 and 56 and I don't think p5 did either.  I changed it to `+=`, but that may not be what you were going for.

This does show another issue though.  On lines 38 and 39 you're calling for a random value between 10 and... 10.  So you're really just assigning a value of 10.  For giggles I changed it to -10 and 10.  This makes our orb move off the screen, but move it does.

Your implode won't work because you're saying "if the posX equals width/2 or if the size equals the size minus the size" ... so there's really nothing there.  You need to declare it using `if(this happens){do this}`-style notation.  Based on what it looks like you're trying to do, you also have the problem that the orb currently always spawns in the center, so even if this worked as intended, you'd just end up imploding the sphere before it goes anywhere.  Giving the orb a random start value and having it bounce off the walls (to keep it on screen) should alleviate this and give you something to work with.

**Comment by erinflint** [comment] 2018-11-08 06:17
Alright Don! Another one for you! I'm just trying to make some circles move around my screen and nothing is showing up. Here is my code:

let circle = [];
let x;
let y;
let size;
let color;
let num_of_circles = 30;

function setup() {
    createCanvas(windowWidth, windowHeight);

    circle = new Circle (random(windowWidth), random(windowHeight), 30, color(random(255), random(255), random(255)));

    for (let i = 0; i < num_of_circles; i++ ) {
        circle[i] = new Circle(random(widowWidth), random(windowHeight), 30, color(random(255), random(255), random(255));
      }
    }

function draw
  background(0);
  for( i = 0; i < num_of_circles; i++ ){
    circle[i].frame();
  }
  }

class Circle {
  constructor(x, y, size, color) {
    this.color = color;
    this.size = size;
    this.rad = this.size / 4;
    this.posX = random(width);
    this.posY = random(height);
    this.deltaX = random(-4, 4);
    this.deltaY = random(-4, 4);
  }
  frame(){
    this.display();
    this.move();
    this.edgeCheck();
  }
  display() {
    push();
    noStroke();
    fill(this.color);
    translate(this.posX, this.posY);
    ellipse(0, 0, this.size);
    pop();
  }
  move() {
    this.posX += this.deltaX;
    this.posY += this.deltaY;
  }
  edgeCheck() {
    if (this.posX + this.rad >= width || this.posX - this.rad <= 0) {
      this.deltaX *= -1;
    }
    if (this.posY + this.rad >= height || this.posY - this.rad <= 0) {
      this.deltaY *= -1;
    }
  }
}

**Comment by erinflint** [comment] 2018-11-08 06:20
circle = new Circle (random(windowWidth), random(windowHeight), 30, color(random(255), random(255), random(255)));

    for (let i = 0; i < num_of_circles; i++ ) {
        circle[i] = new Circle(random(widowWidth), random(windowHeight), 30, color(random(255), random(255), random(255)));
      }
lines 11-15 look like this FYI, for some reason they got cut off in my first post

**Comment by hayliesunshine** [comment] 2018-11-08 06:28
I'm getting an error code that says that 'class' cannot be used, it is only available in ES6. I also had to change all of my 'let's to 'var' because of the same error code. Anyone know what's up with that?

I also still can't get anything to show up, although now my background color is there.

**Comment by JoleneTiffanyG** [comment] 2018-11-08 06:33
Don you are just the coolest.

**Comment by hayliesunshine** [comment] 2018-11-08 06:34
^True

**Comment by hayliesunshine** [comment] 2018-11-08 06:36
![capture3](https://user-images.githubusercontent.com/42792278/48181722-dee8ff80-e2e5-11e8-97f4-a2a8f1358d3e.JPG)
![capture4](https://user-images.githubusercontent.com/42792278/48181726-e0b2c300-e2e5-11e8-8af4-1dd9f0cb1f5d.JPG)
 This is the new version of my code.

**Comment by DVSnell** [comment] 2018-11-08 06:40
I'll start with the easy one for @hayliesunshine :
So what's happening here is your error detector (the "linter" in Atom) is trying to make sure the code will work on older browsers that may not support ES6 yet.  Apart from some really old browsers this shouldn't be a problem.  You can still code with ES6 in mind, and it will work in our modern browsers, but it will pass those errors.

So how do you get rid of them?  If you're using the linter that was recommended at the beginning of class, it's pretty easy.  In Atom's navigation area on the left side of the screen, `Right click` or `CMD+click` on the folder you're currently writing code int and choose `New File`.  Enter `.jshintrc` and hit enter.  In that new file put a single line saying `{"esversion": 6}`.  This tells the linter to detect errors using the new ES6 standards.

Like This: 
![jshintrc](https://user-images.githubusercontent.com/39629030/48181891-7fd7ba80-e2e6-11e8-9b99-23fa90334646.png)

One caveat:  You need this file in *every* folder you write code in.  It doesn't have to be uploaded to GitHub, though so you could always tell GitHub Desktop to ignore it.  Uploading it doesn't hurt anything, either so it's up to you.

**Comment by DVSnell** [comment] 2018-11-08 06:51
@hayliesunshine So you're partway there.  You're still trying to call your object properties as functions.  Take Line 65, for example.  `this.base_rect()` is a function.  You'll want to use `rect(this.base_rectX, this.base_rectY, this.base_rectW, this.base_rectH)` on that line.  It will draw a `rect` with the settings you use from lines 39 to 42.   You'll have to repeat the same thing for your ellipses, too.

Then you can remove Line 29 entirely.  Basically on 29, you're trying to store a shape as a variable and... well, that can''t be done here.

**Comment by DVSnell** [comment] 2018-11-08 07:05
@erinflint  First, an easy mistake:  Line 18.  Gotta get that `draw` function established properly with some `()` and a `{`  Next up, on line 11 and again on 14, you're trying to use `color` but p5 thinks you want to use it as a function.  14 is also trying to reference `widowWidth` which seems rather rude, to be honest ;).

But now we get to a big one.  On Line 27 (and line 5, 26, and 43) you are establishing the variable and property `color`.  The problem is that p5 already uses `color`.  Namely, as a function to assign colors.  This throws all kinds of funkiness at you, so we need to change it.  I just made it `shade` but we still have an issue.  It's trying to give it a non-numerical value of `color` (or `shade` in mine), so it's defaulting to ... well, not a number.  So on line 27 I put `this.shade = 255` as an example and now I've got a whole swarm of white circles bouncing around doin' their thing!

**Comment by erinflint** [comment] 2018-11-08 07:12
Thank you so much! Could you possibly post a screenshot of the tweaks you made so I can compare mine? I applied the changes you suggested but am still coming up with nothing.

**Comment by JoleneTiffanyG** [comment] 2018-11-08 07:14
Okay this is a weird question but I've fixed every possible problem in several different sketches and all I could get to show up is the background.  So out of curiosity I Literally copied and pasted my friend's project into a new sketch, and I just get the background.  And on his link with the exact same code there is all kinds of movement and it works just fine.  Is there any possible reason this could be happening that makes sense?

**Comment by DVSnell** [comment] 2018-11-08 07:15
Blam!
![blam](https://user-images.githubusercontent.com/39629030/48183255-4ce3f580-e2eb-11e8-95e9-4d601013f2ac.png)

**Comment by erinflint** [comment] 2018-11-08 07:18
I've fixed everything and still no cigar. Thank you so much for your help though, Don!

**Comment by DVSnell** [comment] 2018-11-08 07:22
@JoleneTiffanyG I've had that happen when I have the wrong `index.html` open or if I've closed it, but left the preview open.  Closing and reopening Atom, selecting the appropriate `index.html` and `sketch.js` followed by activating the preview and keeping both tabs open seemed to fix it.

Otherwise, it might be a browser-related issue so trying a different one might help.

**Comment by DVSnell** [comment] 2018-11-08 07:23
@erinflint Well, there might be a simple syntax error hiding somewhere.  What do you have for code right now?  Screenshot-wise, I mean.

**Comment by erinflint** [comment] 2018-11-08 07:25
![screen shot 2018-11-08 at 12 25 05 am](https://user-images.githubusercontent.com/42758837/48183699-d6e08e00-e2ec-11e8-9c22-fc35321b5f29.png)
![Uploading Screen Shot 2018-11-08 at 12.25.15 AM.png…]()

**Comment by JoleneTiffanyG** [comment] 2018-11-08 07:28
Okay I gave up on what I was trying to do before, I don't see what's wrong with this new one though and I'm just getting a black canvas and nothing else
![screenshot 29](https://user-images.githubusercontent.com/42923897/48183809-3b035200-e2ed-11e8-8cd0-8ac54247d894.png)
![screenshot 30](https://user-images.githubusercontent.com/42923897/48183810-3b035200-e2ed-11e8-9289-8f40a2f62995.png)

**Comment by DVSnell** [comment] 2018-11-08 07:29
@erinflint Ah.  It's still trying to create the variable `color` on Line 5.  I bet that's it.  Also, that `0` on Line 26, might be unnecessary.

**Comment by erinflint** [comment] 2018-11-08 07:31
SWEET JESUS thank you so much Don!

**Comment by DVSnell** [comment] 2018-11-08 08:03
@JoleneTiffanyG So there's a few issues here, but it might be due to the lateness of the hour and code fatigue at this point lol.

Firstly, we're incorrectly calling some variables.  On Line 17, we call for `orb_color` which doesn't exist except in the Orbs object.  Giving it a color value works, or assigning a global variable with a different name will work too.

Next up, you have `framerate` instead of `frameRate` on Line 18.  Easy fix.

Line 20 calls for `orb.size` but that doesn't exist anywhere in the code.  And I think you're really looking for `orb.length`

Double check it against this:
![blam2](https://user-images.githubusercontent.com/39629030/48185379-0a71e700-e2f2-11e8-817a-68daa7d2e400.png)

**Comment by JoleneTiffanyG** [comment] 2018-11-08 08:15
Did it work when you had that ^ written?  I still can't get it to work like that

**Comment by DVSnell** [comment] 2018-11-08 08:17
Yeah, that preview is live.  I've got the funky ellipses falling downwards.  Are you opening the right `index.html` in your browser?  And which browser are you using?  Switching to a different one might yield better results.

**Comment by JoleneTiffanyG** [comment] 2018-11-08 08:20
Using Chrome, def hitting the right index.  I'll try another browser.. btw why aren't the ellipses green?  Or is that just how it's looking to me

**Comment by JoleneTiffanyG** [comment] 2018-11-08 08:26
Oh My God I GOT IT!  Thank you so so so so much for your help!!!!!!

**Comment by DVSnell** [comment] 2018-11-08 08:27
Yeah, the color thing was my bad.  Used tildes instead of apostrophes so it assigned a value of 255 to them.  It's green when I change them.

**Closed as completed** 2018-11-14 23:33 UTC
