### ISSUE TITLE
if/else question

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#168] opened 2018-10-16 23:53 UTC
Hey everyone, hope everyone's projects are going well..

I have a question on how to do an 'if else' while loop with my program idea.

I have some preliminary code done up, screenshot of code updated as of 5:49PM today..

And am wondering how to incorporate the while loop with the if else statement in the program.

I am trying to have it create a random number between 1 and 30, and if the number is less than 15, it'll do the first series of ellipses, and if it's greater than 15, to do the other set of shapes.

So...my questions are:

1. How do I get it to let me create the variable storage for the random function? it doesn't seem to like 'var1' for some reason...and I think I did that for HW-6.

2. How do I incorporate the while loop as I described above into it, once that is done, I will be trying to have it display the number it comes up with, to test the code. (if time allows).

Thanks guys, and good luck on your assignments this week, just took an exam in American Gov't :(
![ss 109](https://user-images.githubusercontent.com/42828220/47053879-522aa600-d16c-11e8-9752-5ef48a0e0b19.PNG)

**Comment by mafordah** [comment] 2018-10-17 06:21
For your first question, unless the picture has some of your code cut off, I don't think you have `var1` defined as a variable yet using either `let var1 =` or `var var1 =`

**Comment by jballas** [comment] 2018-10-17 14:52
@HagenNathaniel you can use the `for()` loop (or `while()` loop) to create your series of ellipses. Instead of writing the `ellipse()` function four times. If you want each ellipse to be another color, I suppose that would have to be another variable.

**Comment by HagenNathaniel** [comment] 2018-10-17 20:41
Thanks guys for the responses. .


On the var front,  I was trying 'let var1 = var1' and 'var1 =var1' as the variable declaration. 

It didn't like either. 

I'm looking into changing the ellipse portion to have them draw offset from the center. ..I can look at an earlier assignment I did to figure that out. 

Now I just need to figure out how to write out the loop, ..

Something I  guess like: 'if var1 = >15, ellipse('canvasWidth /2, canvasHeight /2, 120, 120);

Else if ......'?

I want to create a bunch of ellipses of various size and color though.. hence my code. This might make things harder.  (Edited)

Any input on my thoughts in this?

**Comment by HagenNathaniel** [comment] 2018-10-18 19:52
So, update!!!

I added the var1 declaration, seems to like the syntax.

I've stared at the error for the if statement, and looked at online (W3 schools) syntax guides, and cannot see why it doesn't accept the statement.

I also am still looking at the idea to create the multiple ellipses for the first 'if statement,' I'm going to add the 'else' statement next, it'll probably hate that too..lol!

Have a look at the new code, the screenshot shows all code :)

![ss 09](https://user-images.githubusercontent.com/42828220/47180023-bd938580-d2dc-11e8-9b59-c9d19914953b.PNG)

**Comment by HagenNathaniel** [comment] 2018-10-18 19:59
yup, it hates it, I'm literally doing it off the syntax rules on W3.

![ss 10](https://user-images.githubusercontent.com/42828220/47180473-e5cfb400-d2dd-11e8-9ca9-7ba7e66953be.PNG)

**Comment by HagenNathaniel** [comment] 2018-10-18 20:00
side note, I find it annoying I don't get email notifications for ANY issue of mine, but for everyone else's I get everything...

**Comment by DVSnell** [comment] 2018-10-18 23:32
The `if` error fix:  Put your "greater than" / "less than" symbols before "equals sign" and remove the space between the two symbols.  So `>=` or `<=`  See if that clears anything up.

Per email notifications:  I just got this in my inbox at 5:30 PM and I check my email almost every hour.  Also depends on if they answer via the email or on Github, I've found.

**Comment by HagenNathaniel** [comment] 2018-10-18 23:59
AHH, makes sense on both counts.

TY sir :)

**Comment by HagenNathaniel** [comment] 2018-10-18 23:59
kinda figured it was a spacing issue..

**Comment by HagenNathaniel** [comment] 2018-10-19 04:04
added the changes you showed me, removed the errors I had.

But, it didn't run correctly, it just showed a blue background, like I had in the setup() function.

Tried to use framerate to see if it was running fast, no, that's not it.

I should explain my idea, the program is intended to continuously run, slowly, so it doesn't give you a seizure. it'll run thru the random function over and over, and each time, display the indicated shapes and color.

Maybe that can help narrow down what I need to fix for you guys?

![ss 13](https://user-images.githubusercontent.com/42828220/47197157-957a4580-d321-11e8-8f99-2a378650a3fb.PNG)

**Comment by DVSnell** [comment] 2018-10-19 07:14
Got a few notes for you:

`framerate` should be camelcased to `frameRate` and p5 doesn't use `canvasWidth` or `canvasHeight`, so use `width` and `height` respectively.  You can replace `Math.floor` and `Math.random` with just `floor` and `random`.

https://p5js.org/reference/ should be your primary source for proper code, since w3 hosts more than just p5 and you might start mixing CSS and HTML into your Java.
https://p5js.org/examples/ is a nice secondary source showing how to actually use the items referenced on the previous page.

Instantiating your variable outside of a looping function (like `draw`) means the value only gets assigned once, so there will be no animation.  If you move line 18, where var1 gets the random, floored number assignment, things should start moving.  Since `function draw` repeats, you'll end up calling a random number and flooring it each time instead of only in the single read-through that `setup` and non-function items get.

Remember order of operations.  Draw your background first in your if/else, then set fill, then draw shapes.  It's like Photoshop layer order but in reverse.  Right now, your backgrounds in the if/else statement are going to overwrite your shapes.

**Comment by HagenNathaniel** [comment] 2018-10-19 15:21
OH!! That makes sense.

So I need to have my variable INSIDE the function for draw, if I am reading your comment right.

Change my order on the if/else statement background/shape order.

obviously I understand the camelcase thing, so that's easy enough to fix.

since the function repeats, I won't need to tell it to do so correct?  it'll run the program until it's halted.

I'll change stuff up as outlined here, and we'll see how that goes.

I'll keep ya updated.

**Comment by HagenNathaniel** [comment] 2018-10-20 00:10
Made the changes, and then it threw up...

looking at the reference you showed, I changed the math, width, height, etc codes.

screenshots are of the errors and the code.

But I THINK I got the relevant stuff in the function chunk of the code


![ss 14](https://user-images.githubusercontent.com/42828220/47248764-fcebd000-d3c9-11e8-9bd4-a890d151a5b4.PNG)
![ss 13](https://user-images.githubusercontent.com/42828220/47248765-fd846680-d3c9-11e8-8de8-b06035efe3ca.PNG)

**Comment by DVSnell** [comment] 2018-10-20 07:56
So right now you're telling p5 that `var1` is an object called `random` with a property of `floor` and that it should use whatever value is in that property.  Since neither the object or property exist, it doesn't know what to do with the error and instead looks for the end of line marker (a semicolon) much earlier than it should.  When it doesn't find it, it gets all rage-y and starts throwing the errors.

The math you'd want to use is for that entire bit is actually `floor((random()*30)+1)`.  This will (in order) generate a random number between 0 and 1, not including 1, multiply that number by 30, add 1 to that new number and then round it down to the nearest integer.

**Comment by HagenNathaniel** [comment] 2018-10-20 15:00
I was wondering about that, the p5 reference doesn't seem to take into account if you want to have a upper and lower 'floor' value. far as I could tell., except that one that had a '30' in ( ).

So, in other words, it isn't a crapton of errors, but one error compounded because the compiler/editor can't figure out what to do with one error.

**Comment by DVSnell** [comment] 2018-10-20 18:15
Yeah, compounded errors are pretty common.  The giveaway was that every error in that screenshot was on line 27 and it kept moving forward only a few characters at a time.  It kept looking for what it expected and couldn't find it, so it would move a bit further and try again until it just had a fit and moved on.  Thankfully, once you plug the one problem, they all tend to go away.  The most common culprits are missing parenthesis and curly brackets, but that one was just a pure syntax error.

As for `floor` (and `ceil`, too) they really are just simple rounders.  You can throw in a `constrain` like `constrain(floor(random(5, 25)), 7, 20)` which would create a random number between 5 and 25, round it down to the nearest whole number and constrain the values between 7 and 20 discarding any values below 7 and above 20.

Another option is to use `int` instead of `floor` so it will round to the nearest whole integer.  So `int(random())` with no value inputs would act as a switch between 0 and 1 since valueless `random` generates between 0.00000 and including 0.999999.  Anything below 0.5 becomes 0 and anything above and including 0.5 becomes 1.

It's a simple, handy binary switch.

**Comment by HagenNathaniel** [comment] 2018-10-20 20:42
alright, let me plug in the fix, and see if it wants to play nice.

Really hoping this starts working soon.

**Comment by HagenNathaniel** [comment] 2018-10-20 21:00
good news is, it now runs...bad news is...

well, I can't show this in a screenshot..

here's a quick vid I made.
[HW-8 vid.zip](https://github.com/Montana-Media-Arts/120_CreativeCoding/files/2498541/HW-8.vid.zip)

It appears to be halfway functional.but is only doing the ellipse statement. I'm looking at the second statement, which is the issue.

I'm trying to get an 'else if' statement to work as well.. with no change in luck..

![ss 15](https://user-images.githubusercontent.com/42828220/47260441-d8026600-d478-11e8-8acd-4db0dc23b9bd.PNG)

**Comment by HagenNathaniel** [comment] 2018-10-21 00:21
edit: I noticed the one issue might be the fact it says 'greater than' in the second and first statement.

BUT, doesn't seem to matter if I change it back the other way.

**Comment by DVSnell** [comment] 2018-10-21 00:25
Easy enough fix.  You're drawing another `background` when the `else` fires after your shape inside the `else` is drawn, so it overwrites the shape.  You can delete lines 42 and 43 and the animation should work as intended.

One thing I noticed while trying your code is that rectangles in p5 draw from the corner, so the upper left corner will be in the center of the screen, and the center of the ellipse.  You can set the rectangle's mode with `rectMode(CENTER)` to make the rectangle draw from its central coordinate instead, so long as that line is called before the rectangle is drawn, if that is the look you're going for.

**Comment by HagenNathaniel** [comment] 2018-10-21 00:28
just noticed my dumb ass forgot to delete the copied code...lol!

Ok, yeah, that's exactly what I am going for!!

So I put that line of code BEFORE the rect() code?

I'll try that out.

**Comment by HagenNathaniel** [comment] 2018-10-21 19:16
The program is now 100% functional!!

**Closed as completed** 2018-10-21 19:16 UTC
